### PR TITLE
Add passthroughs

### PR DESCRIPTION
**Pull request by floored1585**
This adds support for configurable pass and pass_persist values in snmpd.conf

### CODE REVIEW

**Comment by floored1585** [comment]
Travis failed due to an external problem, if you could re-run the build it should pass...

**Comment by floored1585** [comment]
Let me know if you need anything else to get this merged in

**Comment by er0** [comment]
We could use this feature too. Any chance this can merge?

One question about the namespace. Don't the pass, pass_persist attributes belong at ['snmp']['pass'] instead of ['snmp']['snmpd']['pass'] ?

**Comment by thomasvincent** [comment]
Merged pull request.

**Pull request closed without merging**
